version: '3'

tasks:

  hello:
    desc: "Hello World from Task!"
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  lint:
    desc: "Lint the Typescript code"
    cmds:
      - npx eslint './**/*.ts'
    silent: true

  lint-contracts:
    desc: "Lint the Solidity contracts"
    cmds:
      - npx solhint 'contracts/**/*.sol'
    silent: true

  compile-contracts:
    desc: "Compile the Solidity contracts"
    cmds:
      - npx hardhat compile
    silent: true

  clean-and-compile-contracts:
    desc: "Clean the compilation directories, then compile the Solidity contracts"
    cmds:
      - npx hardhat clean
      - npx hardhat compile
    silent: true

  reset:
    desc: "Completely reset the NodeJS Hardhat environment"
    cmds:
      - npm run reset
    silent: true

  test:
    desc: "Run the development tests on a temporary Hardhat node"
    # Alternative commands:
    # npx hardhat test --typecheck
    # npm exec -- mocha --require ts-node/register test/**/*.ts
    # Example of use:
    # task test -- --grep "should deploy" --debug
    # ^ Note the extra "--" before the arguments to pass CLI_ARGS to the command.
    cmds:
      - npm exec -- mocha --require ts-node/register test/**/*.ts {{.CLI_ARGS}}
    silent: true

  show-example-script-commands:
    desc: "Show the example script commands"
    cmds:
      - cat example-script-commands.txt
    silent: true

  check-formatting:
    desc: "Check the formatting of the Typescript code"
    cmds:
      - npx prettier --config .prettierrc './**/*.ts' --check
    silent: true

  fix-formatting:
    desc: "Reformat the Typescript code"
    cmds:
      - npx prettier --config .prettierrc './**/*.ts' --write
    silent: true

  lint:
    desc: "Lint the Typescript code"
    cmds:
      - npx eslint './**/*.ts'
    silent: true

  start-local-node:
    desc: "Start a local Hardhat node"
    cmds:
      - npx hardhat node
    silent: true

  check-network-connections:
    desc: "Check the connections to the various Ethereum networks"
    cmds:
      - npm run --silent ts-node scripts/check-network-connections.ts
    silent: true

  hello-world-get-message:
    cmds:
      - npm run --silent ts-node scripts/HelloWorld/get-message.ts -- {{.CLI_ARGS}}
    silent: true

